#!/usr/bin/env Rscript

get_rmd_title = function (rmd_file)
    rmarkdown::yaml_front_matter(rmd_file)$title

filename = commandArgs(trailingOnly = TRUE)[1]

message('Uploading ', dQuote(filename), ' to RPubs')

source_filename = sub('\\.nb\\.html$', '.rmd', filename)
rsc_config_filename = sprintf('rsconnect/documents/%s/rpubs.com/rpubs/Document.dcf',
                              source_filename)
rsc_record = read.dcf(rsc_config_filename)

if (nchar(rsc_record[1, 'title']) == 0L)
    rsc_record[1, 'title'] = get_rmd_title(source_filename)

result = rsconnect::rpubsUpload(rsc_record[1, 'title'],
                                filename, source_filename,
                                id = rsc_record[1, 'bundleId'])

if (! is.null(result$error))
    stop(result$error)

rsc_record[1, 'when'] = as.numeric(as.POSIXct(Sys.time()))
write.dcf(rsc_record, rsc_config_filename)

message('🔗 ', result$continueUrl)

# vim: ft=r
